# Site wide configuration

title: Stephan Hoyer
description: "Computational scientist and software developer."
locale: en_US
url: https://stephanhoyer.com
# url: http://localhost:4000
image:
  feature: fractal-header.jpg

# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Stephan Hoyer
  avatar: stephan-hoyer.jpg
  bio: "Physicist, computational scientist and software engineer."
  email:
  disqus-shortname: shoyer
  twitter: shoyer
  facebook: #username
  google:
    plus: #username
    analytics: UA-9101891-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: shoyer
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: stephanhoyer
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess", ".well-known"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
